language: java
before_install: 
  - mvn install:install-file -DgroupId=blojsom -DartifactId=blojsom-core -Dversion=3.2 -Dpackaging=jar -Dfile=lib/blojsom-core-3.2.jar
  - mvn install:install-file -DgroupId=blojsom -DartifactId=blojsom-plugins -Dversion=3.2 -Dpackaging=jar -Dfile=lib/blojsom-plugins-3.2.jar
  - mvn install:install-file -DgroupId=blojsom -DartifactId=blojsom-core -Dversion=2.32 -Dpackaging=jar -Dfile=lib/blojsom-core-2.32.jar
  - mvn install:install-file -DgroupId=flickrj -DartifactId=flickrapi -Dversion=1.0a8 -Dpackaging=jar -Dfile=lib/flickrapi-1.0a8.jar
  - mvn install:install-file -DgroupId=kaptcha -DartifactId=kaptcha -Dversion=1.1 -Dpackaging=jar -Dfile=lib/kaptcha-1.1.jar
  - mvn install:install-file -DgroupId=markdownj -DartifactId=markdownj -Dversion=1.0.2b4-0.3.0 -Dpackaging=jar -Dfile=lib/markdownj-1.0.2b4-0.3.0.jar
script: "mvn clean test package site:site"
